export const personalInfo = {
  name: 'Dhruv Ghosh',
  firstName: 'Dhruv',
  lastName: 'Ghosh',
  title: 'Math + AI @ Carnegie Mellon University',
  tagline: 'Building at the intersection of mathematics, artificial intelligence, and finance',
  interests: ['Quant Finance', 'AI/ML', 'Software Engineering'],
  email: 'dghosh2@andrew.cmu.edu',
  linkedin: 'https://www.linkedin.com/in/ghoshdhruv/',
  github: 'https://github.com/dghosh-2',
  location: 'Pittsburgh, PA',
};

export const experiences = [
  {
    id: 1,
    role: 'ML/Optimization Research Assistant',
    company: 'CMU Prism Lab',
    description: 'FELIX - Research on biological superintelligence, developing machine learning and optimization algorithms for complex biological systems.',
    logo: '/Prism.jpg',
    isPresent: true,
  },
  {
    id: 2,
    role: 'Backend Software Developer Intern',
    company: 'Goalday',
    description: 'Built an AI Email Agent for construction project managers, automating communication workflows and improving operational efficiency.',
    logo: '/goalday.jpg',
    isPresent: false,
  },
  {
    id: 3,
    role: 'AI & Software Developer Intern',
    company: 'Routed AI',
    description: 'Developed a career networking tool leveraging AI to connect professionals and optimize career pathways.',
    logo: '/routed.jpg',
    isPresent: false,
  },
  {
    id: 4,
    role: 'Undergraduate Researcher',
    company: 'Carnegie Mellon University',
    description: 'NLP research focused on privacy valuation reasoning, analyzing how natural language processing can be applied to understand privacy preferences.',
    logo: '/CMU.jpg',
    isPresent: false,
  },
  {
    id: 5,
    role: 'Full Stack Software Developer',
    company: 'CMU Scotty Labs',
    description: 'Developed Labrador and CMU Marketplace - full-stack applications serving the Carnegie Mellon community.',
    logo: '/scottylabs.jpg',
    isPresent: false,
  },
  {
    id: 6,
    role: 'Equity Research Analyst',
    company: 'CMU Tartan Student Fund',
    description: 'TMT sector analyst for a student-run investment group, conducting equity research and investment analysis.',
    logo: '/tartanstudentfund.jpg',
    isPresent: false,
  },
  {
    id: 7,
    role: 'Executive Board Member',
    company: 'CMU Introductory Finance Societies',
    description: 'Led initiatives in sales & trading and quantitative finance education for undergraduate students.',
    logo: '/introductoryfinancesociety.jpg',
    isPresent: false,
  },
  {
    id: 8,
    role: 'Private Equity Intern',
    company: 'Caprae Capital',
    description: 'Deal sourcing for lower/middle market private equity transactions, evaluating investment opportunities.',
    logo: '/caprae.jpg',
    isPresent: false,
  },
];

export const projects = [
  {
    id: 1,
    name: 'PolicyReady',
    tagline: 'Automated Healthcare Compliance',
    description: 'A full-stack compliance automation tool for healthcare organizations. Upload PDF questionnaires and get instant MET/NOT_MET assessments against your policy database. Features keyword extraction via GPT-4, inverted index search across policy documents, and structured output with verbatim evidence quotes and citations.',
    frontend: ['Next.js', 'TypeScript'],
    backend: ['Python', 'FastAPI'],
    apis: ['OpenAI API', 'PyMuPDF'],
    deployed: true,
    deployUrl: 'https://policy-ready.vercel.app',
    githubUrl: 'https://github.com/dghosh-2/PolicyReady',
    color: 'royal',
  },
  {
    id: 2,
    name: 'InsightAgent',
    tagline: 'Enterprise NLP for PDF info extraction',
    description: 'A full-stack NLP search and retrieval tool for PDF question-answering. Upload PDFs, ask natural language questions, and get grounded answers with citations. Features FAISS vector search with local embeddings, cross-encoder reranking for improved relevance, and LLM-powered answers with confidence scores.',
    frontend: ['React', 'TypeScript', 'TailwindCSS'],
    backend: ['Python', 'FastAPI'],
    apis: ['OpenAI API', 'FAISS', 'sentence-transformers'],
    deployed: true,
    deployUrl: 'https://insight-agent-red.vercel.app',
    githubUrl: 'https://github.com/dghosh-2/InsightAgent',
    color: 'gold',
  },
  {
    id: 3,
    name: 'HeartHelper',
    tagline: 'ML-powered heart disease prediction',
    description: 'A full-stack application featuring a custom MLP Neural Network built with PyTorch to predict heart disease from medical parameters. The model includes ReLU activation functions, learning rate scheduling, feature engineering, and comprehensive data preprocessing for accurate health predictions.',
    frontend: ['Next.js', 'TypeScript'],
    backend: ['Python', 'PyTorch'],
    apis: ['PyTorch nn', 'Cleveland Heart Dataset'],
    deployed: false,
    deployUrl: '',
    githubUrl: 'https://github.com/dghosh-2/HeartHelper',
    color: 'royal',
  },
  {
    id: 4,
    name: 'Rat Challenge',
    tagline: 'Is there a rat in my food?',
    description: 'A full-stack application that combines food delivery order data with NYC Restaurant Inspection Results to uncover financial risks tied to food safety. The dashboard analyzes rodent violations, revenue at risk, health grades, and provides a watchlist of high-risk restaurants. Downloads of reports available.',
    frontend: ['Next.js', 'JavaScript'],
    backend: ['Python'],
    apis: ['NYC Restaurant Safety API'],
    deployed: true,
    deployUrl: 'https://rat-challenge.vercel.app',
    githubUrl: 'https://github.com/dghosh-2/RatChallenge',
    color: 'gold',
  },
  {
    id: 5,
    name: 'MarketScout',
    tagline: 'AI for better investing',
    description: 'Your personal assistant for AI-driven equity research reports. A full-stack equity research application designed to enable users to make better decisions about investing. Receive downloadable and customizable equity research reports with live and dynamic portfolio management.',
    frontend: ['Next.js', 'JavaScript'],
    backend: ['Python'],
    apis: ['YFinance API', 'OpenAI API', 'SQLAlchemy'],
    deployed: true,
    deployUrl: 'https://market-scout-chi.vercel.app',
    githubUrl: 'https://github.com/dghosh-2/Market-Scout',
    color: 'royal',
  },
  {
    id: 6,
    name: 'SkyDrift',
    tagline: 'Balloon Constellation Tracker',
    description: 'Real-time analytics tool tracking 1000 weather balloons from Windborne Systems. Integrated with real-time, live storm and fire data for comprehensive analysis. Implemented features like custom zone tracking, balloon position predictions, and more.',
    frontend: ['Next.js', 'TypeScript'],
    backend: ['Python', 'FastAPI'],
    apis: ['Windborne API', 'NASA FIRMS API', 'OpenWeatherMap'],
    deployed: true,
    deployUrl: 'https://sky-drift.vercel.app',
    githubUrl: 'https://github.com/dghosh-2/SkyDrift',
    color: 'gold',
  },
];

export const about = {
  academic: {
    school: 'Carnegie Mellon University',
    highSchool: 'Lynbrook High School',
    location: 'Pittsburgh, PA',
    degree: 'Mathematics and Artificial Intelligence',
    clubs: [
      { name: 'Sales & Trading Academy', note: '1 of 2 selected in Spring 2025' },
      { name: 'Quant Club' },
    ],
    coursework: {
      math: ['3D Calculus', 'Matrices & Linear Algebra', 'Game Theory', 'Discrete Math', 'Counting & Graph Theory', 'Math Finance', 'Multivariate Analysis', 'Integration & Approximation'],
      cs: ['Fundamentals of Programming', 'Data Structures & Algorithms', 'Functional Programming', 'Computer Systems', 'Probability & Computing'],
    },
  },
  interests: ['Quant Finance', 'AI/ML', 'Software Engineering'],
  personal: [
    { title: 'Weightlifting' },
    { title: 'Basketball' },
    { title: 'Music', note: 'all-state musician' },
    { title: 'Football' },
    { title: 'Boxing' },
    { title: 'Sneakers' },
    { title: 'Classic Movies' },
    { title: 'Table Tennis' },
  ],
};

export const navItems = [
  { name: 'Home', href: '#home' },
  { name: 'Experience', href: '#experience' },
  { name: 'Projects', href: '#projects' },
  { name: 'About', href: '#about' },
  { name: 'Contact', href: '#contact' },
];
