export const personalInfo = {
  name: 'Dhruv Ghosh',
  firstName: 'Dhruv',
  lastName: 'Ghosh',
  title: 'Math + AI @ Carnegie Mellon University',
  tagline: 'Building at the intersection of mathematics, artificial intelligence, and finance',
  interests: ['Quant Finance', 'AI/ML', 'Software Engineering'],
  email: 'dghosh2@andrew.cmu.edu',
  linkedin: 'https://www.linkedin.com/in/ghoshdhruv/',
  github: 'https://github.com/dghosh-2',
  location: 'Pittsburgh, PA',
};

export const experiences = [
  {
    id: 1,
    role: 'Software Engineering Intern',
    company: 'Magnetar Capital',
    logo: '/magnetar.jpg',
    period: 'June 2026 - Present',
    isPresent: true,
  },
  {
    id: 2,
    role: 'Applied Machine Learning Research Assistant',
    company: 'CMU Prism Lab',
    logo: '/Prism.jpg',
    period: 'Jan - May 2026',
    isPresent: false,
  },
  {
    id: 3,
    role: 'Backend Software Developer Intern',
    company: 'Goalday',
    logo: '/goalday.jpg',
    period: 'May - Aug 2025',
    isPresent: false,
  },
  {
    id: 4,
    role: 'AI & Software Developer Intern',
    company: 'Routed AI',
    logo: '/routed.jpg',
    period: 'Aug - Oct 2025',
    isPresent: false,
  },
  {
    id: 5,
    role: 'Undergraduate Researcher',
    company: 'Carnegie Mellon University',
    logo: '/CMU.jpg',
    period: 'June - Jul 2025',
    isPresent: false,
  },
  {
    id: 6,
    role: 'Equity Research Analyst',
    company: 'CMU Tartan Student Fund',
    logo: '/tartanstudentfund.jpg',
    period: 'Jan - May 2025',
    isPresent: false,
  },
];

export const projects = [
  {
    id: 1,
    name: 'PolicyReady',
    tagline: 'Automated Healthcare Compliance',
    description: 'A full-stack compliance automation tool for healthcare organizations. Upload PDF questionnaires and get instant MET/NOT_MET assessments against your policy database. Features keyword extraction via GPT-4, inverted index search across policy documents, and structured output with verbatim evidence quotes and citations.',
    frontend: ['Next.js', 'TypeScript'],
    backend: ['Python', 'FastAPI'],
    apis: ['OpenAI API', 'PyMuPDF'],
    deployed: true,
    deployUrl: 'https://policy-ready.vercel.app',
    githubUrl: 'https://github.com/dghosh-2/PolicyReady',
    color: 'royal',
  },
  {
    id: 2,
    name: 'InsightAgent',
    tagline: 'Enterprise NLP for PDF info extraction',
    description: 'A full-stack NLP search and retrieval tool for PDF question-answering. Upload PDFs, ask natural language questions, and get grounded answers with citations. Features FAISS vector search with local embeddings, cross-encoder reranking for improved relevance, and LLM-powered answers with confidence scores.',
    frontend: ['React', 'TypeScript', 'TailwindCSS'],
    backend: ['Python', 'FastAPI'],
    apis: ['OpenAI API', 'FAISS', 'sentence-transformers'],
    deployed: true,
    deployUrl: 'https://insight-agent-red.vercel.app',
    githubUrl: 'https://github.com/dghosh-2/InsightAgent',
    color: 'gold',
  },
  {
    id: 3,
    name: 'HeartHelper',
    tagline: 'ML-powered heart disease prediction',
    description: 'A full-stack application featuring a custom MLP Neural Network built with PyTorch to predict heart disease from medical parameters. The model includes ReLU activation functions, learning rate scheduling, feature engineering, and comprehensive data preprocessing for accurate health predictions.',
    frontend: ['Next.js', 'TypeScript'],
    backend: ['Python', 'PyTorch'],
    apis: ['PyTorch nn', 'Cleveland Heart Dataset'],
    deployed: true,
    deployUrl: 'https://heart-helper.vercel.app',
    githubUrl: 'https://github.com/dghosh-2/HeartHelper',
    color: 'royal',
  },
  {
    id: 4,
    name: 'Rat Challenge',
    tagline: 'Is there a rat in my food?',
    description: 'A full-stack application that combines food delivery order data with NYC Restaurant Inspection Results to uncover financial risks tied to food safety. The dashboard analyzes rodent violations, revenue at risk, health grades, and provides a watchlist of high-risk restaurants. Downloads of reports available.',
    frontend: ['Next.js', 'JavaScript'],
    backend: ['Python'],
    apis: ['NYC Restaurant Safety API'],
    deployed: true,
    deployUrl: 'https://rat-challenge.vercel.app',
    githubUrl: 'https://github.com/dghosh-2/RatChallenge',
    color: 'gold',
  },
  {
    id: 5,
    name: 'MarketScout',
    tagline: 'AI for better investing',
    description: 'Your personal assistant for AI-driven equity research reports. A full-stack equity research application designed to enable users to make better decisions about investing. Receive downloadable and customizable equity research reports with live and dynamic portfolio management.',
    frontend: ['Next.js', 'JavaScript'],
    backend: ['Python'],
    apis: ['YFinance API', 'OpenAI API', 'SQLAlchemy'],
    deployed: true,
    deployUrl: 'https://market-scout-chi.vercel.app',
    githubUrl: 'https://github.com/dghosh-2/Market-Scout',
    color: 'royal',
  },
  {
    id: 6,
    name: 'SkyDrift',
    tagline: 'Balloon Constellation Tracker',
    description: 'Real-time analytics tool tracking 1000 weather balloons from Windborne Systems. Integrated with real-time, live storm and fire data for comprehensive analysis. Implemented features like custom zone tracking, balloon position predictions, and more.',
    frontend: ['Next.js', 'TypeScript'],
    backend: ['Python', 'FastAPI'],
    apis: ['Windborne API', 'NASA FIRMS API', 'OpenWeatherMap'],
    deployed: true,
    deployUrl: 'https://sky-drift.vercel.app',
    githubUrl: 'https://github.com/dghosh-2/SkyDrift',
    color: 'gold',
  },
  {
    id: 7,
    name: 'AlphaStream',
    tagline: 'Financial Market Data Pipeline',
    description: 'A production-oriented financial market data platform. Python workers ingest public market data, RabbitMQ streams raw and normalized events, PostgreSQL stores relational data, Redis caches hot reads, FastAPI exposes a REST API, and a Go gateway adds edge rate limiting and response caching.',
    frontend: ['Python', 'nginx'],
    backend: ['FastAPI', 'Go', 'RabbitMQ'],
    apis: ['YFinance', 'FRED API', 'EDGAR', 'AlphaVantage'],
    deployed: false,
    deployUrl: '',
    githubUrl: 'https://github.com/dghosh-2/AlphaStream',
    color: 'royal',
  },
  {
    id: 8,
    name: 'RecruitLikeAPro',
    tagline: 'All-in-one job tracking platform',
    description: 'A full-stack recruitment tracking and job management platform. Features end-to-end application tracking, status management, and recruitment pipeline visualization to streamline the job search process.',
    frontend: ['Next.js', 'TypeScript'],
    backend: ['Next.js'],
    apis: [],
    deployed: true,
    deployUrl: 'https://recruit-tracker-pi.vercel.app',
    githubUrl: 'https://github.com/dghosh-2/RecruitLikeAPro',
    color: 'gold',
  },
  {
    id: 9,
    name: 'RecruiterPro',
    tagline: 'LLM-powered recruitment tracker',
    description: 'An HTML-parsing and LLM-backed recruitment tracking application. Automatically parses job listing pages and uses language models to extract, categorize, and organize job application data.',
    frontend: ['JavaScript'],
    backend: ['Node.js'],
    apis: ['OpenAI API'],
    deployed: false,
    deployUrl: '',
    githubUrl: 'https://github.com/dghosh-2/RecruiterPro',
    color: 'royal',
  },
  {
    id: 10,
    name: 'LoggerBoggers',
    tagline: 'TartanHacks 2026 Hackathon Project',
    description: 'A full-stack application built at TartanHacks 2026, Carnegie Mellon\'s annual hackathon. Built with a modern TypeScript and Next.js stack with a Python backend.',
    frontend: ['Next.js', 'TypeScript'],
    backend: ['Python'],
    apis: [],
    deployed: false,
    deployUrl: '',
    githubUrl: 'https://github.com/dghosh-2/LoggerBoggers',
    color: 'gold',
  },
];

export const about = {
  academic: {
    school: 'Carnegie Mellon University',
    highSchool: 'Lynbrook High School',
    location: 'Pittsburgh, PA',
    degree: 'Mathematics and Artificial Intelligence',
    clubs: [
      { name: 'Sales & Trading Academy', note: '1 of 2 selected in Spring 2025' },
      { name: 'Quant Club' },
    ],
    coursework: {
      math: ['3D Calculus', 'Matrices & Linear Algebra', 'Game Theory', 'Discrete Math', 'Counting & Graph Theory', 'Math Finance', 'Multivariate Analysis', 'Integration & Approximation'],
      cs: ['Fundamentals of Programming', 'Data Structures & Algorithms', 'Functional Programming', 'Computer Systems', 'Probability & Computing'],
    },
  },
  interests: ['Quant Finance', 'AI/ML', 'Software Engineering'],
  personal: [
    { title: 'Weightlifting' },
    { title: 'Basketball' },
    { title: 'Music', note: 'all-state musician' },
    { title: 'Football' },
    { title: 'Boxing' },
    { title: 'Sneakers' },
    { title: 'Classic Movies' },
    { title: 'Table Tennis' },
  ],
};

export const navItems = [
  { name: 'Home', href: '#home' },
  { name: 'Experience', href: '#experience' },
  { name: 'Projects', href: '#projects' },
  { name: 'About', href: '#about' },
  { name: 'Contact', href: '#contact' },
];
